### ISSUE TITLE
support negative margin/padding values

### ISSUE THREAD

**Issue by jameslnewell** [jameslnewell/styled-components-spacing#14]

**Comment by lauriejones** [comment]
Yes please! Updated the title as you cannot have negative padding.

The safest way currently to add something of a "gutter" between inline items or a grid is with a negative margin on the parent to offset the children margins:

```css
.parent {
  margin-left: -1rem;
}

.child {
  margin-left: 1rem;
}
```

Not sure what the nicest API would be. Maybe something like this?

```jsx
const Parent = styled.div`
  ${ml(-4)};
`;

const Child = styled.div`
  ${ml(4)};
`;
```

Then for all the margin mixins we could wrap `${getSpacingFromTheme(key, theme)}` with a little `positiveOrNegative` function
